#lang racket

(define (make-account balance password)
  (let ((incorrect-password-count 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (error . args)
      (set! incorrect-password-count (+ incorrect-password-count 1))
      (if (> incorrect-password-count 7)
          (call-the-cops)
          "Incorrect password"))
    (define (dispatch pw m)
      (if (eq? pw password)
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown request: MAKE-ACCOUNT" m)))
          error))
    dispatch))

(define (call-the-cops) "call the cops.")

; 테스트
(define acc (make-account 100 'abcd))
((acc 'abcde 'withdraw) 40)
((acc 'abcde 'withdraw) 40)
((acc 'abcde 'withdraw) 40)
((acc 'abcde 'withdraw) 40)
((acc 'abcde 'withdraw) 40)
((acc 'abcde 'withdraw) 40)
((acc 'abcde 'withdraw) 40)
((acc 'abcde 'withdraw) 40)